schema_version = "1.0.0"

id = "merge_project_plus"
version = "0.1.3"
name = "BIM: Merge Project Plus"
tagline = "Requires Bonsai (BIM) · Merge linked + manual IFC files into one"
maintainer = "Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"
type = "add-on"
tags = ["Import-Export", "Scene"]
website = "https://github.com/ffribeiro/MergIfcProjectsPlus"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-2.0-or-later"]

[build]
paths_exclude_pattern = [
  ".git/",
  "__pycache__/",
  "*.png",
  "*.zip",
]